name: docs

on:
  pull_request:
    paths:
      - '.github/workflows/site.yaml'
      - 'site_jaspr/**'

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: site_jaspr

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: 📦 Install Jaspr CLI
        run: dart pub global activate jaspr_cli

      - name: 📦 Install Dependencies
        run: dart pub get

      - name: 🔍 Analyze
        run: dart analyze lib/

      - name: 👷 Build
        run: jaspr build --verbose
